### ISSUE TITLE
Docx is not working

### ISSUE THREAD

**Issue by akshayvdongave** [Alcumus/react-doc-viewer#72] opened 2021-02-12 14:15 UTC
Hello,
i am trying to show docx type document but it showing error.
![Screenshot 2021-02-12 194148](https://user-images.githubusercontent.com/67629531/107778796-8299a380-6d6a-11eb-8aca-539a06b4580f.png)

for this is used code 
const docs = [
        { uri: "http://localhost:8080/UploadDocs/sampleDoc.docx" },
        { uri: "http://localhost:8080/UploadDocs/sampleformat1032.rtf" },
        { uri: "http://localhost:8080/UploadDocs/sapmle123.txt" },
        { uri: "http://localhost:8080/UploadDocs/143.pdf" }
        // { uri: require("D:/Apache Software Foundation/Tomcat 8.5/webapps/UploadDocs/143.pdf") }, // Local File
    ];
    return (
        <DocViewer
            pluginRenderers={DocViewerRenderers}
            documents={docs} />
    );

please correct me if wrong or please give solution on it

**Comment by mattmogford-alcumus** [comment] 2021-02-12 14:18
Duplicate of #66

**Closed by mattmogford-alcumus** 2021-02-12 14:18 UTC

**Comment by akshayvdongave** [comment] 2021-02-18 09:27
@mattmogford-alcumus 
can you please give any sample code for custom renderer for docx or any type .
in documentation i got for image but i am got get solution for docx.
please help me for create custom renderer for docx

**Comment by mattmogford-alcumus** [comment] 2021-02-18 09:33
@akshayvdongave  A custom renderer in the context of this package is very simple and documented.
A custom renderer for Microsoft files is 1000x more complex. The included Microsoft renderers will render uploaded documents , but not local documents.

**Comment by ilkou** [comment] 2021-09-21 18:30
this library uses an external service to render documents, this external service cannot recognize local files,

Example:

```
external-service.com/src=http://localhost:8080/your-file.docx
```

in this case, the `external-service` has no access to your `local` files so u should provide a  complete accessible URL,
something like:

```
http://your-website-name:8080/your-file.docx
```

OR

```
http://your-IP-address:8080/your-file.docx
```

**Comment by MMahendra001ScaleTech** [comment] 2022-05-07 07:14
Worked this way : 
Give fileType 
fileType: 'docx' 

```
      const urlData = !!path ? [{ uri: path, fileType: 'docx' }] : [];

        <DocViewer
          className="doc-viewer"
          documents={urlData}
          config={{
            header: {
              disableHeader: false,
              disableFileName: false,
              retainURLParams: false,
            },
          }}
          pluginRenderers={DocViewerRenderers}
        />

```

**Comment by AjayIrkal23** [comment] 2022-11-21 13:20
i am facing a issue with react-doc-viewer in nextjs i am getting this err 

resolve you may need an appropriate loader to handle this file type , currently no loaders are configured to process this file."
please help

**Comment by prem-pachouri-infopro** [comment] 2023-03-23 03:27
@akshayvdongave This video may help you.
https://www.youtube.com/watch?v=E0aK6CKsSNg
